export type TemplateCategory =
  | "general"
  | "tech"
  | "data"
  | "student"
  | "business"
  | "research"
  | "specialized";

export type LayoutStyle =
  | "single-column"
  | "compact"
  | "executive"
  | "left-rail"
  | "clean-grid";

export type HeaderStyle =
  | "centered"
  | "left-aligned"
  | "bold-band"
  | "technical-mono"
  | "minimal-split";

export type HeadingStyle =
  | "underlined"
  | "left-accent"
  | "pill-tag"
  | "plain-caps"
  | "monospace-bracket";

export interface TemplateDefinition {
  id: string;
  name: string;
  category: TemplateCategory;
  tagline: string;
  description: string;
  badge: string;
  bestFor: string;
  atsSafe: boolean;
  layoutStyle: LayoutStyle;
  headerStyle: HeaderStyle;
  headingStyle: HeadingStyle;
  fontFamily: string;
  recommendedColor: string;
}

export const TEMPLATE_CATEGORIES: { id: TemplateCategory; label: string; count: number }[] = [
  { id: "general", label: "General Professional", count: 10 },
  { id: "tech", label: "Software & Technology", count: 10 },
  { id: "data", label: "Data & Analytics", count: 5 },
  { id: "student", label: "Students & Freshers", count: 5 },
  { id: "business", label: "Business & Management", count: 5 },
  { id: "research", label: "Academic & Research", count: 5 },
  { id: "specialized", label: "Specialized & Industry", count: 10 },
];

export const TEMPLATES_REGISTRY: TemplateDefinition[] = [
  // 1–10: General Professional
  {
    id: "classic",
    name: "Classic Professional",
    category: "general",
    tagline: "The timeless ATS standard",
    description: "Traditional serif typography with centered header and clean horizontal dividers. Universally recognized by all ATS scanners.",
    badge: "ATS Gold Standard",
    bestFor: "Corporate, Banking, Legal, Administration, Government",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "centered",
    headingStyle: "underlined",
    fontFamily: "Georgia, serif",
    recommendedColor: "#1e3a8a",
  },
  {
    id: "modern",
    name: "Modern Professional",
    category: "general",
    tagline: "Sleek and well-structured",
    description: "Contemporary sans-serif typography with vertical accent border lines and clean date alignments.",
    badge: "Most Popular",
    bestFor: "Managers, Marketers, Product, Sales, Technology",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "left-aligned",
    headingStyle: "left-accent",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#2563eb",
  },
  {
    id: "minimal",
    name: "Clean Minimal",
    category: "general",
    tagline: "Whitespace and typographic clarity",
    description: "Ultra-clean structure with subtle labels, generous breathing room, and zero clutter.",
    badge: "Recruiter Favorite",
    bestFor: "Executives, Designers, Writers, Consultants",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "left-aligned",
    headingStyle: "plain-caps",
    fontFamily: "system-ui, sans-serif",
    recommendedColor: "#0f172a",
  },
  {
    id: "professional",
    name: "Executive Band",
    category: "general",
    tagline: "Authority and executive presence",
    description: "Prominent top header band with structured grid layout for leadership competencies and achievements.",
    badge: "Executive Pick",
    bestFor: "Directors, VPs, Senior Consultants, General Managers",
    atsSafe: true,
    layoutStyle: "executive",
    headerStyle: "bold-band",
    headingStyle: "underlined",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#065f46",
  },
  {
    id: "corporate-clean",
    name: "Corporate Standard",
    category: "general",
    tagline: "Engineered for Fortune 500 applications",
    description: "Crisp corporate styling with prominent section divides, high readability, and standardized ATS sections.",
    badge: "Enterprise Safe",
    bestFor: "Finance, Insurance, HR, Corporate Operations",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "left-aligned",
    headingStyle: "underlined",
    fontFamily: "Arial, sans-serif",
    recommendedColor: "#1e293b",
  },
  {
    id: "recruiter-friendly",
    name: "Recruiter Friendly",
    category: "general",
    tagline: "Optimized for the 6-second scan",
    description: "High-contrast headings, bold company names, and immediate skill visibility in the top third.",
    badge: "Fast Review",
    bestFor: "Fast-paced hiring pipelines and high-volume roles",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "centered",
    headingStyle: "pill-tag",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#0284c7",
  },
  {
    id: "traditional-serif",
    name: "Traditional Serif",
    category: "general",
    tagline: "Conservative, formal elegance",
    description: "Classic Garamond-style layout tailored for law firms, universities, and conservative boardrooms.",
    badge: "Formal Standard",
    bestFor: "Law, Academia, Real Estate, Wealth Management",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "centered",
    headingStyle: "plain-caps",
    fontFamily: "Georgia, serif",
    recommendedColor: "#334155",
  },
  {
    id: "contemporary",
    name: "Contemporary Clean",
    category: "general",
    tagline: "Balanced and forward-looking",
    description: "Modern layout balancing clean lines, subtle pill tags for skills, and clear date badges.",
    badge: "Modern Balanced",
    bestFor: "Agencies, SaaS, High-growth startups",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "left-aligned",
    headingStyle: "left-accent",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#4f46e5",
  },
  {
    id: "formal-executive",
    name: "Formal Executive",
    category: "general",
    tagline: "For seasoned C-suite and VP candidates",
    description: "Emphasizes career trajectory, governance highlights, and organizational scope.",
    badge: "C-Suite Standard",
    bestFor: "Chief Executives, Senior Partners, Managing Directors",
    atsSafe: true,
    layoutStyle: "executive",
    headerStyle: "centered",
    headingStyle: "underlined",
    fontFamily: "Georgia, serif",
    recommendedColor: "#1e1b4b",
  },
  {
    id: "compact-one-page",
    name: "One-Page Compact",
    category: "general",
    tagline: "Maximum punch on a single sheet",
    description: "Carefully calibrated margins and line-heights to fit substantial career history on one sheet.",
    badge: "1-Page Guarantee",
    bestFor: "Early to mid-career candidates targeting a single page",
    atsSafe: true,
    layoutStyle: "compact",
    headerStyle: "minimal-split",
    headingStyle: "plain-caps",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#0f172a",
  },

  // 11–20: Software / Technology
  {
    id: "technical",
    name: "Software Engineer",
    category: "tech",
    tagline: "Engineered for developers",
    description: "Monospace highlights, categorized tech stacks, GitHub callouts, and project architecture summaries.",
    badge: "Tech Standard",
    bestFor: "Software Engineers, DevOps, Data Scientists, Architects",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "technical-mono",
    headingStyle: "monospace-bracket",
    fontFamily: "monospace, sans-serif",
    recommendedColor: "#0284c7",
  },
  {
    id: "fullstack-dev",
    name: "Full Stack Developer",
    category: "tech",
    tagline: "Frontend to backend mastery",
    description: "Structured layout highlighting frontend, backend, database proficiencies, and deployed live apps.",
    badge: "Developer Pick",
    bestFor: "Full Stack, React/Node Engineers, Web Architects",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "left-aligned",
    headingStyle: "left-accent",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#0d9488",
  },
  {
    id: "frontend-focus",
    name: "Frontend Engineer",
    category: "tech",
    tagline: "UI/UX, performance, and interaction",
    description: "Spotlights web vitals, state management, CSS architecture, and portfolio links.",
    badge: "UI Specialist",
    bestFor: "Frontend Developers, Design Engineers, React Specialists",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "left-aligned",
    headingStyle: "pill-tag",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#7c3aed",
  },
  {
    id: "backend-systems",
    name: "Backend Systems",
    category: "tech",
    tagline: "Scalability, microservices, and databases",
    description: "Emphasizes throughput, uptime percentages, API design, and distributed systems.",
    badge: "Systems Architect",
    bestFor: "Backend Engineers, Platform Engineers, Cloud Specialists",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "technical-mono",
    headingStyle: "underlined",
    fontFamily: "monospace, sans-serif",
    recommendedColor: "#1e293b",
  },
  {
    id: "devops-cloud",
    name: "DevOps & SRE",
    category: "tech",
    tagline: "Infrastructure as Code & CI/CD",
    description: "Spotlights Kubernetes, Terraform, cloud certifications, and automated deployment pipelines.",
    badge: "Infra Standard",
    bestFor: "Site Reliability Engineers, Cloud Architects, Platform Ops",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "left-aligned",
    headingStyle: "monospace-bracket",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#ea580c",
  },
  {
    id: "cloud-architect",
    name: "Cloud Architect",
    category: "tech",
    tagline: "AWS, Azure, GCP infrastructure leadership",
    description: "Showcases cloud certifications, migration cost-savings, and enterprise multi-region architecture.",
    badge: "Cloud Certified",
    bestFor: "AWS / Azure Solutions Architects, Principal Engineers",
    atsSafe: true,
    layoutStyle: "executive",
    headerStyle: "bold-band",
    headingStyle: "underlined",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#0284c7",
  },
  {
    id: "cybersecurity",
    name: "Cybersecurity & SecOps",
    category: "tech",
    tagline: "Compliance, pentesting, and defense",
    description: "Clear callouts for CISSP, CEH, security clearances, zero-trust architectures, and incident response.",
    badge: "Security Standard",
    bestFor: "Security Analysts, Penetration Testers, InfoSec Leads",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "left-aligned",
    headingStyle: "plain-caps",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#991b1b",
  },
  {
    id: "mobile-dev",
    name: "Mobile App Developer",
    category: "tech",
    tagline: "iOS, Android, React Native & Flutter",
    description: "Features App Store download metrics, user review scores, and device compatibility stacks.",
    badge: "Mobile Specialist",
    bestFor: "iOS Developers, Android Engineers, Cross-Platform Leads",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "left-aligned",
    headingStyle: "pill-tag",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#059669",
  },
  {
    id: "qa-automation",
    name: "QA & Automation",
    category: "tech",
    tagline: "End-to-end testing and quality engineering",
    description: "Highlights test coverage percentages, Playwright/Cypress frameworks, and regression time cuts.",
    badge: "Quality Engineering",
    bestFor: "SDET, QA Automation Engineers, Test Leads",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "left-aligned",
    headingStyle: "left-accent",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#0284c7",
  },
  {
    id: "systems-programmer",
    name: "Systems Programmer",
    category: "tech",
    tagline: "C, C++, Rust, Embedded & OS",
    description: "Focused on low-level performance, memory safety, concurrency, and hardware interfaces.",
    badge: "Low-Level Systems",
    bestFor: "Embedded Systems, Firmware, Kernel Engineers, Game Engine Devs",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "technical-mono",
    headingStyle: "monospace-bracket",
    fontFamily: "monospace, sans-serif",
    recommendedColor: "#334155",
  },

  // 21–25: Data / Analytics
  {
    id: "data-analyst",
    name: "Data Analyst",
    category: "data",
    tagline: "Insights, dashboards, and quantitative impact",
    description: "Clean sections for SQL, BI tools, statistical methods, and quantified business outcomes.",
    badge: "Analytics Standard",
    bestFor: "Data Analysts, BI Developers, Operations Analysts",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "left-aligned",
    headingStyle: "left-accent",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#0369a1",
  },
  {
    id: "data-scientist",
    name: "Data Scientist",
    category: "data",
    tagline: "ML models, predictive analytics, and Python",
    description: "Highlights model metrics, AUC/F1 scores, feature engineering, and scientific Python packages.",
    badge: "AI / ML Pick",
    bestFor: "Data Scientists, Machine Learning Engineers, NLP Researchers",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "left-aligned",
    headingStyle: "underlined",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#6d28d9",
  },
  {
    id: "data-engineer",
    name: "Data Engineer",
    category: "data",
    tagline: "Warehouses, ETL, and streaming pipelines",
    description: "Callouts for Snowflake, Databricks, Spark, Kafka, and data lake architecture.",
    badge: "Big Data Standard",
    bestFor: "Data Engineers, Analytics Engineers, Database Architects",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "technical-mono",
    headingStyle: "monospace-bracket",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#0f766e",
  },
  {
    id: "business-analyst",
    name: "Business Analyst",
    category: "data",
    tagline: "Bridging business goals and technical specs",
    description: "Emphasizes process re-engineering, stakeholder management, and financial projections.",
    badge: "Business Analysis",
    bestFor: "Business Analysts, Product Analysts, Strategy Associates",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "centered",
    headingStyle: "underlined",
    fontFamily: "Arial, sans-serif",
    recommendedColor: "#1e3a8a",
  },
  {
    id: "bi-engineer",
    name: "BI & Reporting",
    category: "data",
    tagline: "Executive dashboards and data storytelling",
    description: "Spotlights Power BI, Tableau, Looker architectures, and automated executive reporting.",
    badge: "BI Dashboard",
    bestFor: "BI Analysts, Reporting Specialists, KPI Architects",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "left-aligned",
    headingStyle: "pill-tag",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#0284c7",
  },

  // 26–30: Students / Freshers
  {
    id: "cs-graduate",
    name: "Computer Science Graduate",
    category: "student",
    tagline: "Education first, coursework, and coding projects",
    description: "Puts academic credentials, coursework, hackathons, and GitHub repositories front and center.",
    badge: "CS Fresher Standard",
    bestFor: "CS Grads, Bootcamp Graduates, Junior Developers",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "centered",
    headingStyle: "left-accent",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#2563eb",
  },
  {
    id: "college-fresher",
    name: "College Fresher",
    category: "student",
    tagline: "Degrees, GPA, and campus leadership",
    description: "Balanced student layout showcasing GPA, awards, student organizations, and internships.",
    badge: "Student Standard",
    bestFor: "University Students, Fresh Grads, Entry-Level Applicants",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "centered",
    headingStyle: "underlined",
    fontFamily: "Georgia, serif",
    recommendedColor: "#1e40af",
  },
  {
    id: "stem-internship",
    name: "STEM Intern",
    category: "student",
    tagline: "Lab experience, research, and technical skills",
    description: "Tailored for college students applying to summer software, engineering, and data internships.",
    badge: "Internship Pick",
    bestFor: "Undergraduates, Engineering Interns, Research Fellows",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "left-aligned",
    headingStyle: "pill-tag",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#0891b2",
  },
  {
    id: "entry-level-general",
    name: "Entry Level Professional",
    category: "student",
    tagline: "Transferable skills and accelerated growth",
    description: "Structured to compensate for shorter tenure by spotlighting quick mastery and project success.",
    badge: "Fast Track",
    bestFor: "Recent Grads, Career Switchers, Junior Associates",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "left-aligned",
    headingStyle: "left-accent",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#3b82f6",
  },
  {
    id: "first-job-starter",
    name: "First Career Starter",
    category: "student",
    tagline: "Foundational resume layout",
    description: "Clean, accessible template emphasizing motivation, education, coursework, and community service.",
    badge: "Starter Standard",
    bestFor: "First-time job seekers, High school / College grads",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "centered",
    headingStyle: "plain-caps",
    fontFamily: "Arial, sans-serif",
    recommendedColor: "#475569",
  },

  // 31–35: Business / Leadership
  {
    id: "product-manager",
    name: "Product Manager",
    category: "business",
    tagline: "User metrics, discovery, and product execution",
    description: "Highlights feature delivery, MAU growth, cross-functional leadership, and agile roadmaps.",
    badge: "PM Favorite",
    bestFor: "Product Managers, Group PMs, Technical Product Leads",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "left-aligned",
    headingStyle: "left-accent",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#4338ca",
  },
  {
    id: "project-manager",
    name: "Project & Program Manager",
    category: "business",
    tagline: "Scrum, PMP, budgets, and milestone delivery",
    description: "Calls out budget sizes managed, delivery velocity, risk mitigation, and certifications.",
    badge: "PMP Standard",
    bestFor: "Project Managers, Scrum Masters, Delivery Leads",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "centered",
    headingStyle: "underlined",
    fontFamily: "Arial, sans-serif",
    recommendedColor: "#1e3a8a",
  },
  {
    id: "operations-lead",
    name: "Operations Director",
    category: "business",
    tagline: "Efficiency, supply chain, and cost optimization",
    description: "Emphasizes operational headcount, margin expansion, vendor contracts, and logistics.",
    badge: "Operations Pick",
    bestFor: "Operations Managers, COOs, Supply Chain Executives",
    atsSafe: true,
    layoutStyle: "executive",
    headerStyle: "bold-band",
    headingStyle: "underlined",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#115e59",
  },
  {
    id: "marketing-growth",
    name: "Growth & Marketing Lead",
    category: "business",
    tagline: "CAC, LTV, revenue growth, and campaign ROI",
    description: "Features quantitative campaign results, conversion rate lifts, and digital ad management.",
    badge: "Growth Marketing",
    bestFor: "Growth Marketers, CMOs, Demand Gen Specialists",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "left-aligned",
    headingStyle: "pill-tag",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#c026d3",
  },
  {
    id: "finance-banking",
    name: "Finance & Banking",
    category: "business",
    tagline: "Financial modeling, valuation, and M&A",
    description: "Conservative format tailored for investment banks, private equity firms, and corporate finance.",
    badge: "Wall Street Standard",
    bestFor: "Financial Analysts, Investment Bankers, Controllers, CFOs",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "centered",
    headingStyle: "underlined",
    fontFamily: "Georgia, serif",
    recommendedColor: "#1e293b",
  },

  // 36–40: Academic / Research
  {
    id: "academic-researcher",
    name: "Academic Researcher",
    category: "research",
    tagline: "Publications, citations, and research grants",
    description: "Traditional academic format prioritizing publications, research appointments, and conference talks.",
    badge: "Academic Gold",
    bestFor: "Professors, Research Scientists, Postdocs",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "centered",
    headingStyle: "plain-caps",
    fontFamily: "Georgia, serif",
    recommendedColor: "#334155",
  },
  {
    id: "postdoc-scholar",
    name: "Postdoctoral Scholar",
    category: "research",
    tagline: "Lab achievements, patents, and grant funding",
    description: "Highlights experimental breakthroughs, collaborative grants, and peer-reviewed journals.",
    badge: "Scholar Pick",
    bestFor: "Postdoctoral Fellows, Laboratory Directors, Principal Investigators",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "centered",
    headingStyle: "underlined",
    fontFamily: "Georgia, serif",
    recommendedColor: "#1e3a8a",
  },
  {
    id: "phd-candidate",
    name: "PhD Candidate",
    category: "research",
    tagline: "Dissertation focus, methodology, and teaching",
    description: "Positions doctoral research, academic advisor details, and university teaching assistantships.",
    badge: "PhD Standard",
    bestFor: "Doctoral Students, Graduate Instructors, Fellowships",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "centered",
    headingStyle: "left-accent",
    fontFamily: "Georgia, serif",
    recommendedColor: "#0f172a",
  },
  {
    id: "clinical-researcher",
    name: "Clinical Researcher",
    category: "research",
    tagline: "Trial phases, protocols, and medical journals",
    description: "Structured around clinical trials, FDA compliance, patient cohorts, and statistical findings.",
    badge: "Clinical Standard",
    bestFor: "Clinical Project Managers, Biostatisticians, Medical Affairs",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "left-aligned",
    headingStyle: "underlined",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#0369a1",
  },
  {
    id: "university-faculty",
    name: "Faculty & Lecturer",
    category: "research",
    tagline: "Curriculum development and pedagogical excellence",
    description: "Showcases courses taught, student evaluation metrics, invited lectures, and department service.",
    badge: "Faculty Standard",
    bestFor: "Lecturers, Adjunct Professors, Department Chairs",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "centered",
    headingStyle: "plain-caps",
    fontFamily: "Georgia, serif",
    recommendedColor: "#1e1b4b",
  },

  // 41–50: Specialized / Industry
  {
    id: "healthcare-clinical",
    name: "Healthcare & Nursing",
    category: "specialized",
    tagline: "Licensures, clinical hours, and patient care",
    description: "Prominently displays RN/MD licenses, BLS/ACLS certifications, department rotations, and EHR software.",
    badge: "Healthcare Standard",
    bestFor: "Registered Nurses, Nurse Practitioners, Medical Residents",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "left-aligned",
    headingStyle: "pill-tag",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#0284c7",
  },
  {
    id: "management-consultant",
    name: "Management Consultant",
    category: "specialized",
    tagline: "Case work, business transformation, and ROI",
    description: "Emphasizes client engagements, strategic frameworks, cost reductions, and executive buy-in.",
    badge: "Consulting Standard",
    bestFor: "McKinsey/BCG/Bain Alumni, Strategy Consultants, Advisory",
    atsSafe: true,
    layoutStyle: "executive",
    headerStyle: "left-aligned",
    headingStyle: "underlined",
    fontFamily: "Georgia, serif",
    recommendedColor: "#065f46",
  },
  {
    id: "sales-account-exec",
    name: "Sales & Account Executive",
    category: "specialized",
    tagline: "Quota attainment, pipeline, and closed-won ARR",
    description: "Showcases quota percentages (e.g. 140% of quota), deal sizes ($1M+ ACV), and territory growth.",
    badge: "Sales Leader",
    bestFor: "Account Executives, Sales Directors, BDR Leads, VPs of Sales",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "left-aligned",
    headingStyle: "left-accent",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#16a34a",
  },
  {
    id: "hr-talent-partner",
    name: "HR & Talent Acquisition",
    category: "specialized",
    tagline: "Time-to-hire, retention, and employee experience",
    description: "Features recruiting metrics, HRIS implementations (Workday), and employer brand initiatives.",
    badge: "People Operations",
    bestFor: "HR Directors, Talent Acquisition Partners, People Leads",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "centered",
    headingStyle: "pill-tag",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#9333ea",
  },
  {
    id: "customer-success",
    name: "Customer Success Lead",
    category: "specialized",
    tagline: "Net Retention Rate (NDR) and onboarding NPS",
    description: "Highlights account renewals, customer lifetime value expansion, and churn reduction.",
    badge: "CS Standard",
    bestFor: "Customer Success Managers, Account Managers, Client Services",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "left-aligned",
    headingStyle: "left-accent",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#2563eb",
  },
  {
    id: "legal-compliance",
    name: "Legal Counsel & Compliance",
    category: "specialized",
    tagline: "Bar admissions, corporate governance, contracts",
    description: "High-precision layout for attorneys, corporate counsels, and regulatory compliance directors.",
    badge: "Legal Standard",
    bestFor: "Attorneys, Legal Counsels, Compliance Officers",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "centered",
    headingStyle: "plain-caps",
    fontFamily: "Georgia, serif",
    recommendedColor: "#1e293b",
  },
  {
    id: "government-public",
    name: "Government & Public Service",
    category: "specialized",
    tagline: "Civil service ratings, clearances, and public policy",
    description: "Formatted for federal USAJOBS submissions, state agencies, and public sector positions.",
    badge: "Federal / Gov Safe",
    bestFor: "Public Policy, Government Officials, Military Transitioning",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "centered",
    headingStyle: "underlined",
    fontFamily: "Arial, sans-serif",
    recommendedColor: "#1e3a8a",
  },
  {
    id: "international-cv",
    name: "International Standard CV",
    category: "specialized",
    tagline: "Standard global multi-page curriculum vitae",
    description: "Clean, universally accepted layout adhering to European, Asian, and Middle Eastern CV conventions.",
    badge: "Global Standard",
    bestFor: "International applicants, Global roles, Relocations",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "left-aligned",
    headingStyle: "underlined",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#0f172a",
  },
  {
    id: "creative-technologist",
    name: "Creative Technologist",
    category: "specialized",
    tagline: "Code meets design, multimedia, and interaction",
    description: "Contemporary layout with clean links to portfolios, design systems, and creative projects.",
    badge: "Creative Tech",
    bestFor: "Creative Coders, WebGL Developers, Interactive Designers",
    atsSafe: true,
    layoutStyle: "single-column",
    headerStyle: "minimal-split",
    headingStyle: "pill-tag",
    fontFamily: "Inter, sans-serif",
    recommendedColor: "#ec4899",
  },
  {
    id: "executive-board",
    name: "Executive Board Director",
    category: "specialized",
    tagline: "Governance, audit committees, and strategic vision",
    description: "Ultra-high-level summary tailored for board advisory appointments and committee chairs.",
    badge: "Boardroom Standard",
    bestFor: "Board Members, Independent Directors, Advisory Committee",
    atsSafe: true,
    layoutStyle: "executive",
    headerStyle: "bold-band",
    headingStyle: "plain-caps",
    fontFamily: "Georgia, serif",
    recommendedColor: "#0f172a",
  },
];

export function getTemplateById(id: string): TemplateDefinition {
  const found = TEMPLATES_REGISTRY.find((t) => t.id === id);
  return found || TEMPLATES_REGISTRY[0];
}

export function getTemplatesByCategory(category?: TemplateCategory): TemplateDefinition[] {
  if (!category) return TEMPLATES_REGISTRY;
  return TEMPLATES_REGISTRY.filter((t) => t.category === category);
}

export function searchTemplates(query: string, category?: TemplateCategory): TemplateDefinition[] {
  const list = getTemplatesByCategory(category);
  if (!query || !query.trim()) return list;

  const q = query.toLowerCase().trim();
  return list.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.tagline.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.bestFor.toLowerCase().includes(q) ||
      t.badge.toLowerCase().includes(q)
  );
}
